import { defineConfig } from 'vitepress'
import fs from 'fs'
import path from 'path'
import YAML from 'yaml'

// The CV data is generated by the Python build (`python -m src.main`).
// `build/infos.localized.yml` contains the already-resolved data for each
// locale (`{ en: ..., fr: ... }`), so the `*_fr` resolution lives only in
// `src/renderer.py` and the site never needs to reimplement it.
const LOCALIZED_PATH = path.resolve(process.cwd(), 'build/infos.localized.yml')
const VIRTUAL_ID = 'virtual:infos'
const RESOLVED_ID = '\0' + VIRTUAL_ID

function loadInfos() {
  return fs.existsSync(LOCALIZED_PATH)
    ? YAML.parse(fs.readFileSync(LOCALIZED_PATH, 'utf-8'))
    : {}
}

// Expose the localized CV data as a virtual module so it works identically in
// dev (`vitepress dev`) and at build time, unlike `define` which is not applied
// to `.vue` files by the dev server.
function infosPlugin() {
  return {
    name: 'cv-infos',
    resolveId(id) {
      if (id === VIRTUAL_ID) return RESOLVED_ID
    },
    load(id) {
      if (id === RESOLVED_ID) {
        return `export default ${JSON.stringify(loadInfos())}`
      }
    },
    handleHotUpdate({ file, server }) {
      // Re-read the YAML when the Python build regenerates it.
      if (file === LOCALIZED_PATH) {
        const mod = server.moduleGraph.getModuleById(RESOLVED_ID)
        if (mod) server.moduleGraph.invalidateModule(mod)
        return [...server.moduleGraph.getModulesByFile(RESOLVED_ID) ?? []]
      }
    }
  }
}

// https://vitepress.dev/reference/site-config

// Base URL path the site is served under. Override with the VITEPRESS_BASE
// environment variable, e.g. `VITEPRESS_BASE=/my/path/ npm run docs:build`.
// Defaults to "/" (site at the domain root). VitePress requires the base to
// start and end with a slash, so we normalize it.
function normalizeBase(raw: string): string {
  let base = raw.trim()
  if (!base.startsWith('/')) base = '/' + base
  if (!base.endsWith('/')) base += '/'
  return base
}

const base = normalizeBase(process.env.VITEPRESS_BASE ?? '/')

export default defineConfig({
  base,
  title: "Ulysse DURAND",
  description: "Ulysse DURAND's Curriculum",
  rewrites: {
    // Expose the French (root) locale under `/fr` as well.
    'fr.md': 'fr/index.md'
  },
  locales: {
    // French is the default locale and is served at the site root.
    root: {
      label: 'Français',
      lang: 'fr'
    },
    en: {
      label: 'English',
      lang: 'en'
    }
  },
  vite: {
    plugins: [infosPlugin()]
  }
})
